#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Scalar-List-Utils
version:      1.14
version_from: lib/List/Util.pm
installdirs:  perl
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
